### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [Jaacky/visualyze#2]
this one is broken:
```js
    for (var i=0; i<graphs.length; i++) {
        queries.push(db.none(insertGraphToFusion, [fusion_id, graphs[i]]));
    }

    db.tx(function(t) {
        return t.batch(queries);
    })
```

you must use `t` context to create those queries, you cannot use `db` to create them and then execute inside a transaction, queries end up in the wrong context, with unpredictable result ;)

**Comment by Jaacky** [comment]
@vitaly-t I'll fix that right now, thanks for your useful feedback! :)

How did you find my project btw?
